name: mesa
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - pip
  - pip:
      - solara
      - mesa[rec]==3.1.5